# Generated by Django 3.2.5 on 2022-03-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
